In [2]:
import numpy as np           #numpy= numreical python

In [3]:
l1=[1,2,3,4]

In [5]:
n1=np.array(l1)    #one diamensional array

In [6]:
n1

array([1, 2, 3, 4])

In [7]:
type(n1)

numpy.ndarray

In [8]:
n2=np.array([[1,2,3,4],[5,6,7,8]])      #two diamensional array

In [9]:
n2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
#numpy array with zeros

In [11]:
n3=np.zeros((2,3))

In [12]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
type(n3)

numpy.ndarray

In [14]:
n4=np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
n5=np.zeros((6,6))
n5

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [16]:
n6=np.zeros((10,10))

In [17]:
n6

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#numpy array with numbers

In [18]:
n7=np.full((3,3),55)
n7

array([[55, 55, 55],
       [55, 55, 55],
       [55, 55, 55]])

In [19]:
n8=np.full((4,4),10)
n8

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [20]:
n9=np.full((4,6),9)
n9

array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [21]:
#numpy array with in range

In [22]:
n1=np.arange(50,101)
n1

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [23]:
n2=np.arange(10,20)
n2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [24]:
n3=np.arange(0,30)
n3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [25]:
n4=np.arange(0,100,5)     #0=start,100=stop,5=step
n4

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80,
       85, 90, 95])

In [26]:
n5=np.arange(0,500,50)
n5

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450])

In [27]:
#numpy array with random numbers

In [28]:
import numpy as np

In [29]:
n1=np.random.randint(0,100,10)
n1

array([18, 50, 83, 94, 72, 53, 54, 51, 82, 88])

In [30]:
n2=np.random.randint(20,200,2)  #20=start 200=stop 2=it shows 2 randoms numbers from given range
n2

array([62, 89])

In [33]:
n3=np.random.randint(100,1000,20)
n3

array([968, 774, 191, 229, 656, 556, 197, 140, 396, 690, 450, 188, 705,
       203, 109, 278, 680, 786, 876, 333])

In [34]:
#checking shape of numpy arrays

In [3]:
import numpy as np

In [4]:
n1=np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
n1.shape    #for checking shape

(2, 4)

In [6]:
l1=[1,2,3,4]
l2=[6,7,8,9]

In [7]:
n1=np.array([l1,l2])
n1

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [8]:
n1.shape

(2, 4)

In [9]:
n1.shape=(4,2)
n1

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [12]:
n1.shape=(8,1)
n1

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [9]])

In [16]:
l1=[10,20,30,40,50]
l2=[50,60,70,80,90]

In [17]:
n1=np.array([l1,l2])
n1

array([[10, 20, 30, 40, 50],
       [50, 60, 70, 80, 90]])

In [18]:
n1.shape

(2, 5)

In [19]:
n1.shape=(5,2)
n1

array([[10, 20],
       [30, 40],
       [50, 50],
       [60, 70],
       [80, 90]])

In [ ]:
#joining numpy array  
#vstack()
#hstack()
#column_stack()

In [21]:
import numpy as np

In [22]:
n1=np.array([1,2,3])

In [23]:
n2=np.array([4,5,6])

In [24]:
np.vstack((n1,n2))     #for vertical stack

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
np.hstack((n1,n2))    #for horizontal stack

array([1, 2, 3, 4, 5, 6])

In [26]:
np.column_stack((n1,n2))   #for columnstack

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
n1=np.array([10,20,30,40,50])
n2=np.array([60,70,80,90,100])
n3=np.array([110,120,130,140,150])

In [29]:
np.vstack((n1,n2,n3))

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [30]:
np.hstack((n1,n2,n3))

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150])

In [31]:
np.column_stack((n1,n2,n3))

array([[ 10,  60, 110],
       [ 20,  70, 120],
       [ 30,  80, 130],
       [ 40,  90, 140],
       [ 50, 100, 150]])

In [32]:
#numpy intersection & diffirence

In [33]:
import numpy as np

In [34]:
n1=np.array([10,20,30,40,50])
n2=np.array([50,60,70,80,90])

In [36]:
np.intersect1d(n1,n2)  #intersect#taking common element

array([50])

In [37]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [39]:
np.setdiff1d(n2,n1)

array([60, 70, 80, 90])

In [40]:
import numpy as np

In [46]:
n1=np.array([2,4,6,8,10])
n2=np.array([4,8,12,16,20])

In [47]:
np.intersect1d(n1,n2)

array([4, 8])

In [48]:
np.setdiff1d(n1,n2)

array([ 2,  6, 10])

In [50]:
np.setdiff1d(n2,n1)

array([12, 16, 20])

In [ ]:
#addtion  #np.sum
#np.sum([n1,n2],axis=0) #for sum of elements of column
#np.sum([n1,n2],axis=1)  #for sum of elements of row

In [51]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])

In [52]:
np.sum([n1,n2])  #for overall sum

210

In [53]:
np.sum([n1,n2],axis=0)   #for sum of elements of coloumn

array([50, 70, 90])

In [54]:
np.sum([n1,n2],axis=1)   #for sum of elements of rows

array([ 60, 150])

In [55]:
import numpy as np

In [56]:
n1=np.array([10,20,30])
n2=np.array([40,50,60])
n3=np.array([70,80,90])

In [57]:
np.sum([n1,n2,n3])

450

In [58]:
np.sum([n1,n2,n3],axis=0)

array([120, 150, 180])

In [59]:
np.sum([n1,n2,n3],axis=1)

array([ 60, 150, 240])

In [60]:
#numpy array mathematics
#basic addition
#basic multiplication
#basic subsraction
#basic divison

In [61]:
import numpy as np

In [62]:
n1=np.array([10,20,30])     #addtion
n1=n1+2
n1

array([12, 22, 32])

In [64]:
n2=np.array([20,40,60])
n2=n2+6
n2

array([26, 46, 66])

In [2]:
import numpy as np

In [3]:
n1=np.array([10,20,30]) #substraction
n2=n1-5
n2

array([ 5, 15, 25])

In [4]:
n2


array([ 5, 15, 25])

In [7]:
n2=np.array([5,15,25])
n3=n2+5
n3

array([10, 20, 30])

In [11]:
n3*3
         #mupltiplication

array([30, 60, 90])

In [9]:
n3/10  #divide

array([1., 2., 3.])

In [ ]:
#mean
#median
#standard deviation


In [12]:
import numpy as np


In [13]:
n1=np.array([10,20,30,40,50,60,70,80,90,100])        #finding mean
np.mean(n1)

55.0

In [14]:
n2=np.array([1,2,3,4,5,6,7,8,9,10])
np.mean(n2)

5.5

In [15]:
n3=np.array([1,2,3])
np.mean(n3)

2.0

In [16]:
#median


In [17]:
n1=np.array([10,20,30,40])
np.median(n1)

25.0

In [18]:
n2=np.array([2,4,6,8,10,12,14,16,18,20])
np.median(n2)

11.0

In [19]:
#standard deviation

In [20]:
n1=np.array([1,2,3,4])
np.std(n1)

1.118033988749895

In [21]:
n2=np.array([5,10,15])
np.std(n2)

4.08248290463863

In [22]:
import numpy as np

In [23]:
n1=np.random.randint(0,100,10)

In [24]:
n1

array([96, 37, 86, 52, 59, 27, 91,  8, 69,  2])

In [25]:
np.mean(n1)

52.7

In [26]:
np.median(n1)

55.5

In [27]:
np.std(n1)

31.987653868328636

In [28]:
#numpy save and load

In [29]:
n1

array([96, 37, 86, 52, 59, 27, 91,  8, 69,  2])

In [30]:
np.save("my_numpy",n1)    #to save numpy array


In [31]:
n2=np.load("my_numpy.npy")   #to loading saved numpy
n2 

array([96, 37, 86, 52, 59, 27, 91,  8, 69,  2])